configuration:
  - Release

platform:
  - Win32
  - x64

before_build:
  - cmd: git -C .. clone -q https://github.com/MediaArea/zlib.git
  - cmd: git -C .. clone -q https://github.com/MediaArea/libxml2.git
  - cmd: git -C .. clone -q https://github.com/MediaArea/libxslt.git
  - cmd: git -C .. clone -q https://github.com/MediaArea/libevent.git
  - cmd: git -C .. clone -q https://github.com/MediaArea/jansson.git
  - cmd: git -C .. clone -q https://github.com/MediaArea/ZenLib.git
  - cmd: git -C .. clone -q https://github.com/MediaArea/MediaInfoLib.git
  - ps: >-
      If ($Env:PLATFORM -Eq "Win32") {
        perl -p '-i.bak' -e 's/..\\..\\..\\..\\Qt5.6-msvc2015\\5.6\\msvc2015/C:\\Qt\\5.7\\msvc2015/g' Project\MSVC2015\GUI\MediaConch_GUI.vcxproj
      } else {
        perl -p '-i.bak' -e 's/..\\..\\..\\..\\Qt5.6-msvc2015_64\\5.6\\msvc2015_64/C:\\Qt\\5.7\\msvc2015_64/g' Project\MSVC2015\GUI\MediaConch_GUI.vcxproj
      }

build:
  project: Project\MSVC2015\MediaConch.sln
  verbosity: quiet
